### PR TITLE
Cu 86b0dyx4k create sign up form carmen peterson

### PR DESCRIPTION
**Pull request by varsvisualizes**
Created Signup.css and filled out the Signup.js page, made a copy of the logo.svg file in the "pages" folder so it would be easily accessible to the React files

### CODE REVIEW

**Comment by allantito** [comment]
Task linked: [CU-86b0dyx4k Create Sign Up Form](https://app.clickup.com/t/86b0dyx4k)

**Comment by varsvisualizes** [comment]
Note - this branch was created with the Login page already made, so it's a branch of that branch. If it's easier, we could close the Login Page pull request in lieu of this one, which has those changes already bundled in.

**Comment by ryanRATM** [comment]
@varsvisualizes creating a branch from a branch is usually not recommended since you increase the risk of a merge conflict. say you make a change in the login-page branch, that you don't replicate in this branch, and merge into main.  so when you eventually merge this branch you'd overwrite the login page currently in main.

**Comment by varsvisualizes** [comment]
@ryanRATM Totally understandable, thanks for the breakdown. Would you like me to recreate the changes on another branch, made based on the dev branch?

**Pull request merged**
