### PR TITLE
Cu 86b0dyx4v create navbar parvathy unnikrishnan

### PR DESCRIPTION
**Pull request by poverty149**

### CODE REVIEW

**Comment by allantito** [comment]
Task linked: [CU-86b0dyx4v Create Navbar](https://app.clickup.com/t/86b0dyx4v)

**Comment by ryanRATM** [comment]
@poverty149 is there supposed to be an index.html file outside of the Frontend folder?

**Comment by poverty149** [comment]
@ryanRATM I'm not sure if it's supposed to be there. In my previous version, I had only kept it within the Frontend folder, but then Carmen had moved it outside. I'm guessing she did this to make it easier for deployment that's why I kept both locations in this commit.

**Comment by varsvisualizes** [comment]
Merging branch - if the styling is not fully complete, we can keep fixing it; I just don't want this to stay hovering and clogging the pipeline.

**Pull request merged**
